@account = {{$processEnv FREEMOBILE_ACCOUNT}}
@apiKey = {{$processEnv FREEMOBILE_API_KEY}}
@baseUrl = https://smsapi.free-mobile.fr

###

// Sends a SMS message to the specified Free Mobile account.
GET {{baseUrl}}/sendmsg
	?user={{account}}
	&pass={{apiKey}}
	&msg=Hello World!

###
