<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace free_mobile;

use \php\Boot;

/**
 * Represents the event parameter used for request events.
 */
class RequestEvent {
	/**
	 * @var Client
	 * The client which initiated the request.
	 */
	public $client;
	/**
	 * @var string
	 * The event name.
	 */
	public $name;
	/**
	 * @var string
	 * The URL of the HTTP request.
	 */
	public $url;

	/**
	 * Creates a new request event.
	 * 
	 * @param string $name
	 * @param Client $client
	 * @param string $url
	 * 
	 * @return void
	 */
	public function __construct ($name, $client, $url) {
		$this->client = $client;
		$this->name = $name;
		$this->url = $url;
	}
}

Boot::registerClass(RequestEvent::class, 'free_mobile.RequestEvent');
