name: main
on: [pull_request, push]
jobs:
  hl:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up HashLink
        uses: cedx/setup-hashlink@v1
      - name: Install dependencies
        run: lix download
      - name: Run tests
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
        run: haxe test_hl.hxml
  java:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16
      - name: Install dependencies
        run: lix download
      - name: Run tests
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
        run: haxe test_java.hxml
  js:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: lix download
      - name: Run tests
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
        run: haxe test_js.hxml
  php:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, intl, mbstring, simplexml, sockets
      - name: Install dependencies
        run: lix download
      - name: Run tests
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
        run: haxe test_php.hxml
